.IX Title "BAOBAB 1"

.TH BAOBAB 1 "June 2020"

.SH "NAME"
\fBbaobab\fR \- A graphical disk usage analyzer for the GNOME desktop

.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
\fBbaobab\fR  [OPTIONS…] [DIRECTORY]

.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\fBbaobab\fR (a.k.a. \fBDisk Usage Analyzer\fR) is able to scan either specific
folders (local and remote) or devices, in order to give the user a tree
representation including each directory size or percentage in the branch. It
also auto-detects any mounted/unmounted device. A graphical representation is
also provided for any selected folder.
.PP

.SH "OPTIONS"

.TP
\fB\-a\fR, \fB\-\-all\-file\-systems\fR
Do not skip directories on different file systems. Ignored if DIRECTORY is not specified.
.TP
\fB\-\-help\fR
Show command line options.
.TP
\fB\-\-version\fR
Output version information and exit.

.SH "BUGS"
Bugs should be reported to the GNOME issue tracker at \m[blue]\fBhttp://gitlab.gnome.org/GNOME/baobab/issues\fR\m[].

.SH "ADDITIONAL INFORMATION"
For further information visit \m[blue]\fBhttps://apps.gnome.org/Baobab/\fR\m[].
